# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('pec_grid_immobile', ['pec-sim'])
    obj.source = 'pec_grid_immobile.cc'
